using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Handles the game screen
/// Created By: NEIL DG
/// </summary>
public class GameScreen : View {

	[SerializeField] private PictureComponent pictureRefCopy;
	[SerializeField] private RectTransform pictureParent;


	[SerializeField] private List<PictureComponent> pictureComponentsSpawned;

	// Use this for initialization
	void Start () {
		this.pictureRefCopy.gameObject.SetActive (false);

		this.InitializeGameBoard ();
		EventBroadcaster.Instance.AddObserver (EventNames.ON_INCREASE_LEVEL, this.OnIncreasedLevel);
	}

	void OnDestroy() {
		EventBroadcaster.Instance.RemoveObserver (EventNames.ON_INCREASE_LEVEL);
	}

	/// <summary>
	/// Initializes the game board based from proposed picture models generated by game meachanic handler. Handles the pairing mechanism.  Guarantees that each model has a pair.
	/// </summary>
	private void InitializeGameBoard() {
		PictureModel[] generatedModels = GameMechanicHandler.Instance.GeneratePictureModels ();
		List<PictureComponent> pictureComponentList = new List<PictureComponent> ();

		for (int i = 0; i < generatedModels.Length * 2; i++) {
			GameObject pictureObject = GameObject.Instantiate (this.pictureRefCopy.gameObject, this.pictureParent);
			pictureObject.gameObject.SetActive (true);
			PictureComponent pictureComponent = pictureObject.GetComponent<PictureComponent> ();
			pictureComponent.Reset ();
			pictureComponentList.Add (pictureComponent);
		}
			
		for (int i = 0; i < generatedModels.Length; i++) {
			int firstIndex = Random.Range (0, pictureComponentList.Count);

			//assign first pair then remove it from the list
			this.pictureComponentsSpawned.Add (pictureComponentList [firstIndex]);
			pictureComponentList [firstIndex].AssignPictureModel (generatedModels [i]);
			pictureComponentList.RemoveAt (firstIndex);

			int secondIndex = Random.Range (0, pictureComponentList.Count);

			//assign second pair then remove it from the list
			this.pictureComponentsSpawned.Add (pictureComponentList [secondIndex]);
			pictureComponentList [secondIndex].AssignPictureModel (generatedModels [i]);
			pictureComponentList.RemoveAt (secondIndex);
		}
	}

	private void OnIncreasedLevel() {
		PictureModel[] generatedModels = GameMechanicHandler.Instance.GeneratePictureModels ();
		int additionalCount = (generatedModels.Length * 2) - this.pictureComponentsSpawned.Count;
		Debug.Log ("Generated models: " +(generatedModels.Length * 2) + " Components spawend: " +this.pictureComponentsSpawned.Count+ " Additional count: " + additionalCount);
		List<PictureComponent> componentList = new List<PictureComponent> ();

		//reset all existing components
		for (int i = 0; i < this.pictureComponentsSpawned.Count; i++) {
			this.pictureComponentsSpawned [i].TweenedReset ();
			componentList.Add (this.pictureComponentsSpawned [i]);
		}

		//instantiate additional components
		for (int i = 0; i < additionalCount; i++) {
			GameObject pictureObject = GameObject.Instantiate (this.pictureRefCopy.gameObject, this.pictureParent);
			pictureObject.gameObject.SetActive (true);
			PictureComponent pictureComponent = pictureObject.GetComponent<PictureComponent> ();
			pictureComponent.Reset ();

			this.pictureComponentsSpawned.Add (pictureComponent);
			componentList.Add (pictureComponent);
		}

		for (int i = 0; i < generatedModels.Length; i++) {
			int firstIndex = Random.Range (0, componentList.Count);

			//assign first pair then remove it from the list
			componentList [firstIndex].AssignPictureModel (generatedModels [i]);
			componentList.RemoveAt (firstIndex);

			int secondIndex = Random.Range (0, componentList.Count);

			//assign second pair then remove it from the list
			componentList [secondIndex].AssignPictureModel (generatedModels [i]);
			componentList.RemoveAt (secondIndex);
		}

	}

	public void OnPauseClicked() {
		ViewHandler.Instance.Show (ViewNames.PAUSE_SCREEN_NAME);
	}

}
